### ISSUE TITLE
crash when installing

### ISSUE THREAD

**Issue by jonareofromrunescape** [hylian-modding/ModLoader64-GUI#40]
Unhandled Error
Error: Cannot find module 'C:/Users/ginab/OneDrive/Documents/modloader64-gui-1.1.60-ia32-win/ModLoader/src/version'
Require stack:
- C:/Users/ginab/OneDrive/Documents/modloader64-gui-1.1.60-ia32-win/resources/app/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Timeout.<anonymous> (C:/Users/ginab/OneDrive/Documents/modloader64-gui-1.1.60-ia32-win/resources/app/index.js:434:21)

**Comment by denoflionsx** [comment]
Don't install the program in OneDrive. It is known to cause bizarre issues.
