### ISSUE TITLE
Unable To Start

### ISSUE THREAD

**Issue by Axo1409** [hylian-modding/ModLoader64-GUI#46]
Unhandled Error
Error: Cannot find module 'F:/Games/Emus/N64/ModLoader/src/version'
Require stack:
- F:/Games/Emus/N64/resources/app/index.js
- 
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Timeout.<anonymous> (F:/Games/Emus/N64/resources/app/index.js:434:21)

I'm getting this when starting the program. This is a clean installation.

**Comment by Axo1409** [comment]
Ok using an older version fixed it!
