### ISSUE TITLE
[Linux] Can't update modloader; certificate has expired

### ISSUE THREAD

**Issue by Skywolf285** [hylian-modding/ModLoader64-GUI#49]
When trying to run modloader64-gui for the first time (following the manual install steps from https://modloader64.com/setup.html)  it is not able to download the requires files due the following error:

```
(node:5738) UnhandledPromiseRejectionWarning: FetchError: request to https://repo.modloader64.com/update/update.json failed, reason: certificate has expired
```

Running Pop!_OS 22.04 LTS x86_64

Full terminal output:
```
./modloader64-gui --no-sandbox
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
TRYING TO UPDATE MODLOADER
(node:6705) UnhandledPromiseRejectionWarning: FetchError: request to https://repo.modloader64.com/update/update.json failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/mnt/linux-games/modloader64/modloader64-gui/resources/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:6705) UnhandledPromiseRejectionWarning: FetchError: request to https://repo.modloader64.com/update/update.json failed, reason: certificate has expired
    at ClientRequest.<anonymous> (/mnt/linux-games/modloader64/modloader64-gui/resources/app/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:6705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
TRYING TO UPDATE PLUGINS
Error: Cannot find module '/mnt/linux-games/modloader64/modloader64-gui/ModLoader/src/version'
Require stack:
- /mnt/linux-games/modloader64/modloader64-gui/resources/app/index.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Timeout.<anonymous> (/mnt/linux-games/modloader64/modloader64-gui/resources/app/index.js:434:21)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/linux-games/modloader64/modloader64-gui/resources/app/index.js',
    undefined
  ]
}
```

**Comment by femalemonkeyman** [comment]
modloader64-gui-1.1.60/resources/app/node_modules/node-fetch/lib/index.js
add:
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
